file=fopen('Trolley.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Trolley. Question ID #', ID);

% assigning random variables

       m=randi([100,200]/10);
       f=randi([10,15])+20;
       t=randi([3,8]);
       
%      calculations
       a=(f-20)/m;
       s=0.5*a*t.^2;

           
numString1 = cloze_numerical((round(a*10)/10), 0.05, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical((round(s*10)/10), 0.05, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>In a grocery store, you push a&nbsp', num2str(m),' kg shopping trolley with a force, P, of&nbsp',num2str(f),' N. Its wheels offer a resistive frictional force of 20 N (as shown in the diagram below).</p>',...
    '<p>If the shopping trolley starts at rest, how far does it move in&nbsp',num2str(t),' seconds?</p>',...
        numString2,' m',...
    '<p>(Give your answer correct to 1.d.p.)</p>',...
    '<p><img src="http://s9.postimg.org/8gmzz1373/trolley.png" alt="" width="304" height="164" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>The resultant force acting on the trolley is equal to:</p>',....
        '<p>$$P-20=',num2str(f),'-20=',num2str(f-20),'N$$.</p>',...
        '<br><p>Newton''s second law states that,</p><p>"A force applied to a body causes an acceleration of that body of a magnitude proportional to the force,',...
            ' in the direction of the force, and inversely proportional to the body''s mass."</p>',...
            '<p>This can be written algebraically as $$F=m\\cdot a$$</p>',...
            '<p>Applying it to this situation,</p>',...
            '<p>$$a=(F/m)=(',num2str(f-20),'/',num2str(m),')=',num2str(round(a*10)/10),'$$ m/s<sup>2</sup></p>',...
            '<p>Then applying one of the equations of motion: $$s=u.t+\\frac{1}{2}.a.t^2$$,</p>',...
            '<p>$$s=\\frac{1}{2}\\times ',num2str(round(a*10)/10),'\\times ',num2str(t),'^2=',num2str(round(s*10)/10),'$$ metres</p>',...
              '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from ''http://a.files.bbci.co.uk/bam/live/content/zrshyrd/large''</p>');
    
    
    hint1 = strcat('<b>HINT</b><p>First calculate the resultant force acting on the trolley, then apply Newton''s second law of motion.</p>');...

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
