file = fopen('Question_6.xml', 'w');
fprintf(file,quiz_start());

mcqStringVertical = cloze_mcq('vertical', 2, ...
        'The Fourier series contains no cosine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions', ...
        'The Fourier series contains no sine functions', 'Correct ! The function f(x) is an even function, and therefore contains no sine functions', ...
        'The Fourier series contains cosine and sine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions', ... 
        'The Fourier series contains no cosine or sine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions');
    
    
questionString = strcat('A rectangular function is expressed mathematically as follows : <br> f(x) = 1&nbsp;&nbsp;&nbsp;for&nbsp;&nbsp;&nbsp;-&pi;/2&nbsp;<&nbsp;x&nbsp;<&nbsp;&pi;/2 <br>',...
                         'f(x) = 0&nbsp;&nbsp;&nbsp;for&nbsp;&nbsp;&nbsp;-&pi;&nbsp;<&nbsp;x&nbsp;<&nbsp;&pi;/2&nbsp;&nbsp;and&nbsp;&nbsp;&pi;/2&nbsp;<&nbsp;x&nbsp;<&nbsp;&pi;','<br><br>',...
                         'Which of the following descriptions of the Fourier series of f(x) is true:<br>',mcqStringVertical);
                     
 feedbackString = strcat('The function f(x) is an even function, and therefore contains no sine functions.');                    
                     
xmlCode = question_cloze(1, ...
        'Fourier series', ... 
        questionString, ...
        feedbackString, ...
        '');
    
%Output
fprintf(file, xmlCode);
fprintf(file, quiz_end()); %xml closing code
fclose(file);