file=fopen('Thermal Conductivity.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Thermal Conductivity. Question ID #', ID);

% parameters and calculations

w=randi([3,8]);
h=randi([3,8]);
d=randi([3,8]);
tc=randi([60,80]);
tb=37;
kf=23;
kt=0.6;

Qa=(kf*w*h*(10^-6)*(tc-tb))/(d*10^-3);
Qa=round(Qa*100)/100;
Qt=Qa*(kt/kf);
Qt=round(Qt*100)/100;

numString1 = cloze_numerical(Qa, 0.005, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical(Qt, 0.005, 'Good job!', 'Incorrect, try again');

questionString = strcat('<p>The figure below describes a cuboid block of material for which there is a temperature difference, $$\\Delta \\:T$$,',...
    ' across a pair of opposite faces, each of area, $$A$$, and separated by a distance $$\\Delta x$$. This will result in a heat flow, $$Q$$ watts, from the hotter',...
    ' surface to the cooler, and the thermal conductivity, $$K$$, of the material (Wm<sup>-1</sup>K<sup>-1</sup>) is given by the equation in the figure.</p><br>',...
    '<img src="http://s1.postimg.org/lsdlacp73/image.jpg" alt="" width="740" height="479" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive">',...
    '<p><br></p><p>A man has a major filling to one of his molars due to decay. The filling is&nbsp',num2str(w),'mm front to back,&nbsp',num2str(h),'mm from side to side,',...
    ' and&nbsp',num2str(d),'mm deep. Modelling the cavity / filling as cuboid in shape (with the above dimensions), what is the rate of heat flow from the outside',...
    ' of the tooth to the core when he drinks a cup of hot coffee of temperature&nbsp',num2str(tc),' <sup>o</sup>C?',...
    ' Body temperature is&nbsp',num2str(tb),'<sup>o</sup>C and the thermal conductivity of the filling material is&nbsp',num2str(kf),' Wm<sup>-1</sup>K<sup>-1</sup>.</p>',...
    '<p>(Please give your answer correct to 2.d.p.)</p>',...
    numString1,'Watts',...
    '<br><p>What was the equivalent heat flow when the tooth was intact, if the thermal conductivity of tooth material is&nbsp',num2str(kt),' Wm<sup>-1</sup>K<sup>-1</sup>?</p>',...
    '<p>(Again please give your answer correct to 2.d.p.)</p>',...
    numString2, 'Watts');

generalFeedbackStr = strcat('<p>The equation given in the question can be rearranged to make the rate of heat flow, $$Q$$, the subject, as follows:</p>',...
    '<br>$$Q=K\\cdot A\\cdot \\frac{\\Delta T}{\\Delta x}$$',...
    '<p><br></p><p>Where $$A$$, the cross sectional area perpendicular to heat flow, =&nbsp',num2str(w),' x&nbsp',num2str(h),' x 10<sup>-6</sup> m<sup>2</sup></p>',...
    '<p>and $$\\Delta x$$, the distance the heat flows, =&nbsp',num2str(d),' x 10<sup>-3</sup> m</p>',...
    '<br><p>For the amalgam therefore:</p>',...
    '<p>$$Q_a$$ =&nbsp(',num2str(kf),' x&nbsp',num2str(w),' x&nbsp',num2str(h),' x 10<sup>-6</sup> x&nbsp',num2str(tc-tb),') / (',num2str(d),'x 10<sup>-3</sup>) =&nbsp<b>',num2str(Qa),' Watts</b>.</p>',...
    '<p>For the intact tooth therefore:</p>',...
    '<p>$$Q_t=Q_a\\cdot \\left(\\frac{K_t}{K_a}\\right)$$ =&nbsp(',num2str(Qa),' x (',num2str(kt),' /&nbsp',num2str(kf),')) =&nbsp<b>',num2str(Qt),' Watts</b>.</p>',...
    '<br><p>That''s why dentists like filling cavities with low thermal conudctivity materials.</p>');

hint1 = strcat('<b>HINT</b><p>Think how the model and equation given above can be applied and adapted to answer this question.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
