file=fopen('AAAdvanced.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('AA- Advanced. Question ID #', ID);
        
    
    V=randi([10,20]);
    T=randi([5,15]);
    R=randi([20,40]);
    r=R/100;
    A=V/(r*T);
    S=(V*V)/0.49;
    E=0.5*V*V;
    U=E/196;

  
numString1 = cloze_numerical((round(A*10)/10), 0.05, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical(round(S), 0.5, 'Good job!', 'Incorrect, try again');
numString3 = cloze_numerical(round(E/1000)*1000, 0.5, 'Good job!', 'Incorrect, try again');
numString4 = cloze_numerical(round(U*100)/100, 0.005, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A 1,000 kg car accelerates from rest to &nbsp',num2str(V),' m/s over &nbsp',num2str(R),' seconds. Its wheels have a radius of &nbsp',num2str(R),' cm',...
    '<p>What is the average angular acceleration of the wheels?</p>',...
    '<p>(Give your answer in rads/s<sup>2</sup> to 1.d.p.)</p>',...
    numString1,...
    '<p>The car now enters a curve at a constant speed of &nbsp',num2str(V),' m/s. What is the radius of the curve if the acceleration felt by the passengers is 0.05g? (g is the acceleration due to gravity).</p>',...
    '<p>(Use a value of g of 9.8 m/s<sup>2</sup>)</p>)',...
    '<p>(Give your answer in metres to the nearest whole number)</p>',...
    numString2,...
    '<p>The car now leaves this curve and applies its brakes until it stops. Calculate the work done by the brakes.</p>',...
    '<p>(Give your answer in kJ to 3.s.f.)</p>',...
    numString3,...
    '<p>If the brakes locked on, instantly stopping the wheels instead of steadily slowing them, then the wheels would no longer spin and the car would skid. Assuming a skid in a straight line, what would the coefficient of friction between the tyres and the road be if the car skidded to a stop over a distance of 20 m on a flat road?</p>',...
    '<p>(Give your answer correct to 2.d.p.)</p>',...
    numString4,...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>Using s = (u*t) + 0.5*a*t<sup>2</sup> gives:</p>',...
    '<p>a = &nbsp',num2str(round(A*100)/100),' m/s<sup>2</sup></p>', ...
    '<p>Using v = u + a*t gives:</p>',...
    '<p>v = &nbsp',num2str(round(V*10)/10),' m/s</p>',...
    '<p>The time taken to cover the remaining &nbsp',num2str(C),' metres = &nbsp',num2str(C),'m / &nbsp',num2str(round(V*10)/10),'m/s = &nbsp', num2str(round(U*10)/10),' seconds.</p>', ...
    '<p>Therefore total time = &nbsp',num2str(round(B*10)/10),' seconds.</p>',...
    '<br><p>The acceleration versus time graph for this race will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image2.png" style="width:100%%; height:auto;">',...
    '<br><p>The speed versus time graph is the integral of the acceleration versus time graph, and will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image3.png" style="width:100%%; height:auto;">',...
    '<br><p>The distance versus time graph is the integral of the speed versus time graph, and will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image4.png" style="width:100%%; height:auto;">');

hint1 = strcat('<p>Recall the relationship between angular velocity and linear velocity, and the relationship between angular velocity and angular acceleration.</p>',...
    '<p>Recall the relationship between radial acceleration and linear velocity.</p>',...
    '<p>Remember that work done = change in kinetic energy, and assume that this work is done solely by friction.');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
