file=fopen('Work.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Work. Question ID #', ID);

% assigning random variables

       f=randi([100,200]);
       x1=randi([10,90])/10;
       x2=randi([10,90])/10;

%      calculations
       k=-1*(f/x1)*100;
       W=-0.5*k*x2.^2/10000;
           
numString1 = cloze_numerical((round(k*10)/10), 0.02*k, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical((round(W*10)/10), 0.02*W, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A force, $$F$$, of&nbsp',num2str(f),' N stretches a spring by a distance, $$x$$, of&nbsp',num2str(x1),' cm.</p>',...
        '<p><br></p><p><img src="http://s15.postimg.org/v1v0b22mz/chap10007.gif" alt="" width="341" height="269" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
        '<p>What is the spring constant, $$k$$, in this case?</p>',...
        '<p>$$k$$ =&nbsp',numString1,' N/m',....
        '<p>How much work would need to be done to stretch this spring by&nbsp',num2str(x2),' cm, from its unstretched position?</p>',...
        '<p>Work =&nbsp',numString2, ' J',...
        '<p>(Please give your answers correct to 1.d.p.)</p>',...
        '<p>(Question ID #',num2str(i),').</p>');
        

generalFeedbackStr = strcat('<p>Remember that Hooke''s Law states $$F=-k.x$$ for the elastic deformation of a spring:</p>',...
            '<p><br></p><p><img src="http://s28.postimg.org/7e2pgg8ql/hooke7.jpg" alt="" width="303" height="151" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
            '<p>Therefore:</p>',...
            '<p>$$k=-\\frac{F}{x}=',num2str(round(k*10)/10),' N/m$$</p>',...
            '<p><br></p><p>Work, $$W$$, is defined as the force, $$F$$, applied to a resistance, multiplied by the displacement, $$x$$, of the resistance in the direction of the force:</p>',...
            '<br><p>$$W=F.x$$</p>',...
            '<br><p>When the magnitude of $$F$$ depends on the value of $$x$$, as is the case here, this expression can be modified slightly:</p>',...
            '<p>$$W=\\int ^x_0F.dx$$</p>',...
            '<p>Which in this case is equal to:</p>',...
            '<p>$$W=\\int ^x_0k.x.dx=\\frac{1}{2}.k.x^2=',num2str(round(W*10)/10),' J$$</p>',...
            '<p>(Remember to convert from cm to m in all of the above calculations)</p>',...
            '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
            '<p>Image 1 adapted from '' http://demo.webassign.net/ebooks/cj6demo/art/images/ssg/c10/chap10007.gif''</p>',...
            '<p>Image 2 adapted from ''http://onlinephys.com/hooke7.gif''</p>');
    
   
   
    hint1 = strcat('<b>HINT</b><p>Apply Hooke''s Law to answer the first part of the question.</p><p>Then integrate the force over the distance over which it is applied to answer the second part of the question.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
