file=fopen('Projectiles-Advanced.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Projectiles-Advanced. Question ID #', ID);
    
    %load image - code this later
    %generating random parameters for question (distance D and time M), and calculating working
    %steps
    
    D=randi([10,30]);
    T=randi([20,40]);
    X=T/2;
    Y=D*1000/T;
    Z=9.8*X;
    W=Z/Y;
    B=atan(W);
    C=B*180/pi;
    V=Z/sin(B);   
    
    E=randi([1510,1550]);
    M=randi([50,70]);
    F=(M/2)*((E^2)-(228484));
    ANS=F/1000000;
 
    numString1 = cloze_numerical((round(V*10)/10), 0.05, 'Good job!', 'Incorrect, try again');
    numString2 = cloze_numerical(round(ANS), 1, 'Good job!', 'Incorrect, try again');
 
questionString = strcat('<p><img src="http://s30.postimg.org/fhkl9ck29/HMS_Belfast_1.jpg" alt="" width="635" height="431" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>',...
    '<p><br></p>HMS Belfast is a warship situated on the River Thames. Its guns are aimed to fire at a motorway service station a distance, $$D$$,&nbsp',num2str(D),' km away.</p>',...
    '<p><br></p><b>1. </b>Assuming no air resistance, and that the ship and service station are at the same height above sea level, at what velocity must the shells leave the guns in order to reach the service station in a time, $$T$$, of&nbsp',num2str(T),' s?</p>',...
    '<p>(Give your answer correct to 1.d.p.)</p>',...
    '<p>(Use a value of g of -9.8 m/s<sup>2</sup>)</p>',...
	'<p>Velocity=&nbsp',numString1,' m/s</p>',...
    '<p><br></p><p><b>2. </b>The maximum firing range of the HMS Belfast front guns at 45 degrees, taking air resistance into account, is stated to be 23.3 km.</p>',... 
    '<p>The stated maximum velocity at which the shells leave the gun is&nbsp',num2str(E),' m/s.</p>',... 
    '<p>Each shell weighs&nbsp',num2str(M),' kg. Calculate the energy loss of the shells due to air resistance when they are fired to the maximum range at 45 degrees.</p>',...
    '<p>(Give your answer correct to 2.s.f.)</p>',...
    '<p>(Again use a value of g of -9.8 m/s<sup>2</sup>)</p>',...
    '<p>Energy Loss=&nbsp',numString2,' MJ</p>',...
    '<p>(Question ID #',num2str(i),').</p>');


hint1 = strcat('<b>HINT</b><p>First of all, work out the velocity in the x-direction, and then obtain an expression for the initial velocity in the y-direction. Then combine these two expressions to calculate the angle of trajectory of the shells, and then their velocity.</p>',...
'<p>For the second question, calculate the initial velocity to achieve the maximum given range with no air resistance, when fired at 45 degrees. Then calculate the difference in kinetic energy between the shells when fired at this speed compared to the speed given in the question.</p>');

generalFeedbackStr = strcat('<p>Let initial velocity = $$V_o$$, and angle of trajectory = $$\\phi$$.</p>',...
    '<p>Applying $$s=u.t+\\frac{1}{2}.a.t^2$$ in the <b>x-direction</b> gives:</p>',...
    '<p>$$',num2str(D*1000),'=V_o.cos(\\phi).',num2str(T),'$$</p>',...
    '<br><p>Where $$s$$ is displacement $$D$$; $$u$$ is initial velocity; $$a$$ is acceleration (which is zero in the x-direction); and $$t$$ is time $$T$$.</p>',...
    '<p>Therefore $$V_o.cos(\\phi)=\\frac{',num2str(D*1000),' }{',num2str(T),' }=',num2str(round(Y*10)/10),'m/s$$</p>',...
    '<br><p>Next, looking at the <b>y-direction</b>, the maximum height attained by the shells occurs at $$\\frac{T }{2 } =',num2str(round(X*10)/10),'$$ s, at which point the shells'' vertical velocity, $$v$$, is zero.</p>',...
    '<br><p>Applying $$v=u+a.t$$ gives:</p>',..., 
    '<p>$$0=V_o.sin(\\phi)+(-9.8\\times ',num2str(round(X*10)/10),')$$</p>',...
    '<p>Therefore:</p>',...
    '<p>$$V_o.sin(\\phi)=9.8\\times ',num2str(round(X*10)/10),'=',num2str(round(Z*10)/10),'$$ m/s.</p>',...
    '<br><p>Using the identity $$tan\\phi =\\frac{sin\\phi }{cos\\phi }$$ gives:</p>',...
    '<p>$$\\frac{V_o.sin(\\phi) }{V_o.cos(\\phi) }=\\frac{',num2str(round(Z*10)/10),' }{',num2str(round(Y*10)/10),' }=',num2str(round(W*1000)/1000),'=tan(\\phi)$$</p>',...
    '<p>Therefore:</p><p>$$\\phi=',num2str(round(C*10)/10),'^o$$</p>',... 
    '<p>Using</p><p>$$V_o=(\\frac{T}{2}.9.8.sin(\\phi))$$</p><p>OR</p><p>$$V_o={\\frac{(1000.D)}{(T.cos(\\phi))}$$</p><p>gives:</p>',...
    '<p>$$V_o=',num2str(round(V*10)/10),'$$ m/s.</p>',...
    '<p><br></p><p></p>To answer the second part of the question we need to find the value of $$V_o$$ that would produce a range of 23.3km with no air resistance:</p>',...
    '<p><img src="http://s4.postimg.org/tw5c1b36l/projectile_motion_clip_image002.gif" alt="" width="418" height="125" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>',...
    '<br><p>Again applying $$s=u.t+\\frac{1}{2}.a.t^2$$ in the <b>x-direction</b> gives:</p>',...
    '<p>$$s=V_o.cos(45).t=23300$$</p><p>Therefore:</p>',...
    '<p>$$(1)$$ $$V_o.t=32951.2$$</p>',...
    '<br><p>Applying $$v=u+a.t$$ in the <b>y-direction</b> at the top of the arc gives:</p>',...
    '<p>$$V_o.sin(45)=g.\\frac{t}{2}$$</p><p>Which can be simplified to:</p>',...
    '<p>$$(2)$$ $$\\frac{V_o}{t}=6.93$$</p>',...
    '<br><p>By dividing equation $$(1)$$ by equation $$(2)$$, we can derive the following expression:</p>',...
    '<p>$$t^2=3362.19$$</p><p>Therefore:</p><p>$$t=69$$ s, and $$V_o=478$$ m/s.</p>',...
    '<p>The next step is to find the difference in kinetic energy between the real conditions and the perfect conditions:</p>',...
    '<p>$$\\Delta KE=(\\frac{1}{2}.m.V_{actual}^2)-(\\frac{1}{2}.m.V_{perfect}^2)$$</p>',...
    '<br><p>$$\\Delta KE=\\frac{1}{2}\\times ',num2str(M),'\\times (',num2str(E),'^2-478^2)=',num2str(F),'$$ J.</p>',...
    '<br><p>$$\\Delta KE=',num2str(round(ANS)),'$$ MJ</p>',...
    '<br><p>(Remember to convert from km to m in all calculations)</p>',...
     '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image 1 adapted from ''http://www.frankharris.co.uk/latest-news/wp-content/uploads/2013/03/hms_belfast_04@gallerymain.jpg''</p>',...
         '<p>Image 2 adapted from ''http://www.alanpedia.com/physics_projectile_motion/projectile_motion_clip_image002.gif''</p>');

    

%Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);


