file=fopen('Atomic Structure.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Atomic Structure. Question ID #', ID);

BCCatoms=(randi([100,900])*1000);
BCCunits=BCCatoms/2;
FCCatoms=randi([100,900])*1000;
FCCunits=FCCatoms/4;
TIO2molecules=randi([100,900])*1000;
TIO2units=TIO2molecules/2;

numString1 = cloze_numerical(BCCunits, 0.5, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical(FCCunits, 0.5, 'Good job!', 'Incorrect, try again');
numString3 = cloze_numerical(TIO2units, 0.5, 'Good job!', 'Incorrect, try again');
numString4 = cloze_numerical(TIO2molecules, 0.5, 'Good job!', 'Incorrect, try again');
numString5 = cloze_numerical(TIO2molecules*2, 0.5, 'Good job!', 'Incorrect, try again');

questionString = strcat('<b>A</b><p>The image below represents the body-centred cubic (BCC) structure, which is a crystal structure adopted by some metals (for example iron and chromium).</p>',...
    '<p><img src="http://s10.postimg.org/6ve785h61/BCC.jpg" alt="" width="375" height="139" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"></p>',...
    '<p>The unit cell (the image furthest to the right) is the building block which is repeated in three dimensions in a crystal of the metal.</p>',...
    'If a crystal of iron is made up of&nbsp',num2str(BCCatoms),' atoms, how many <i>unit cells</i> will there be in the crystal?</p><p>',...
    numString1,...
    '</p><b>B</b><p>The image below represents the face-centred cubic (FCC) structure, which is a crystal structure adopted by some metals (for example aluminium and copper).</p>',...
    '<p><img src="http://s10.postimg.org/cm4dlvp61/fcc.jpg" alt="" width="376" height="136" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"></p>',...
    '<p>The unit cell (the image furthest to the right) is the building block which is repeated in three dimensions in a crystal of the metal.</p>',...
    '<p>If a crystal of copper is made up of&nbsp',num2str(FCCatoms),' atoms, how many <i>unit cells</i> will there be in the crystal?</p><p>',...
    numString2,...
    '</p><b>C</b><p>The image below represents a unit cell of titanium dioxide (TiO<sub>2</sub>), which is repeated in three dimensions in a crystal of the ceramic.</p>',...
    '<p><img src="http://s10.postimg.org/3ptlhxyjt/tio2.jpg" alt="" width="274" height="157" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"></p>',...
    '<p>If a crystal of titanium dioxide is made up of&nbsp',num2str(TIO2molecules),' molecules, how many <i>unit cells</i> will there be in the crystal?</p><p>',...
    numString3,...
    '</p><p>How many titanium <i>atoms</i> will there be in this crystal?</p><p>',...
    numString4, ...
    '</p><p>How many oxygen <i>atoms</i> will there be in this crystal?</p><p>',...
    numString5);

generalFeedbackStr = strcat('<b>A</b><p>Each unit cell of a BCC structure contains 1 central atom, and an eighth of an atom in each of the 8 corners, making a total of 2 atoms per unit cell.</p>',...
        '<b>B</b><p>Each unit cell of a FCC structure contains half of an atom on each of the six faces, and an eighth of an atom in each of the 8 corners, making a total of 4 atoms per unit cell.</p>',...
        '<b>C</b><p>Each unit cell of titanium dioxide contains the following:</p>',...
        '<p>Titanium - 1 central atom and an eighth of an atom in each corner, making a total of 2 titanium atoms per unit cell.</p>',...
        '<p>Oxygen - 2 central atoms and two half atoms on each of the top and bottom faces, making a total of 4 oxygen atoms per unit cell.</p>',...
        '<p>One molecule of titanium dioxide contains 1 atom of titanium, and 2 atoms of oxygen. Therefore 1 unit cell of titanium dioxide contains 2 molecules of titanium dioxide.</p>');

hint1 = strcat('<b>HINT</b><p>Calculate the number of atoms (of each element in part C) in each unit cell.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
