file=fopen('Power.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Power. Question ID #', ID);

% assigning random variables

       v=randi([50,100]);
       f=randi([450,600]);

%      calculations
       v1=v*5/18;
       p=v1*f/1000;
       
           
numString1 = cloze_numerical((round(p*10)/10), 0.02*p, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A car travels at a constant speed of&nbsp',num2str(v),' km/hr.',...
        ' It encounters a retarding force (rolling resistance, air resistance etc) of&nbsp',num2str(f),' N.</p>',...
        '<p><br></p><p><img src="http://s28.postimg.org/hvkhngsot/car.gif" alt="" width="350" height="244" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
        '<p>At what power level does the engine deliver energy to the wheels to maintain the car''s speed?</p>',...
        '<p>',numString1,' kW',....
        '<p>(Please give your answer correct to 1.d.p.)</p>',...
        '<p>(Question ID #',num2str(i),').</p>');
        

generalFeedbackStr = strcat('<p>Power, $$P$$, can be defined as the amount of work, $$W$$, performed in a given time, $$t$$:</p>',...
        '<p>$$P=\\frac{W}{t}$$</p>',...
        '<br><p>But work is also the product of force, $$F$$, and distance, $$x$$. Therefore:</p>',...
        '<p>$$P=\\frac{F.x}{t}$$</p>',...
        '<br><p>But $$\\frac{x}{t}$$ is equal to velocity, $$v$$. Therefore:</p>',...
        '<p>$$P=F.v=',num2str(round(p*10)/10),' kW$$</p>',...
        '<br><p>(Don''t forget to convert from km/hr to m/s)</p>',...
          '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from ''http://www.bbc.co.uk/staticarchive/9db0c22dbd8ec3a3c905dc8a854168e44c14035e.gif''</p>');
    
  

   
    hint1 = strcat('<b>HINT</b><p>Remember to use SI units in all parts of this question.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
