file=fopen('Amontons.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Amontons. Question ID #', ID);

m=randi([1688,2193])/1000;
us=(log(m))*2/pi;
x1=randi([10,20]);
y1=m*x1+10;
x2=randi([70,90]);
y2=m*x2+10;

% To plot  graph
figure(1)
plot([x1,x2],[y1,y2],'linewidth',2,'Color','red');
hold on
%Axes and titles
axis([0 x2+10 0 y2+10])
grid minor
grid on
% title('Friction Between Fabric and Skin','FontSize',14, 'FontWeight','bold');
ylabel('Force (N)','Fontsize',12,'FontWeight','bold');
xlabel('m_{2}.g (N)','Fontsize',12,'FontWeight','bold');
hold off
%Plot string generation
plotString1= generateImageString(gcf, 'image1');

numString1 = cloze_numerical((round(us*1000)/1000), 0.0005, 'Good job!', 'Incorrect, try again');

questionString = strcat('Amontons'' law states that the force needed to initiate slip between two surfaces ($$F_s$$), i.e. to overcome static friction, is a fixed proportion of the normal force ($$N$$) ',...
    ' between the two surfaces.</p><p> These two parameters are related by the coefficient of static friction ($$\\mu _s$$) as follows:',...
    '<p>$$\\mu _s=\\frac{F_s}{N}$$',...
    '<br><p>An experiment was carried out as per the diagram below, where a weight of mass m<sub>2</sub> was suspended over a subject''s forearm by a section of nonwoven fabric.',...
    '<p><img src="http://s29.postimg.org/lfp2zo413/picture.jpg" alt="" width="704" height="310" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>',...
    '<p>The mass of the weight was varied, and the force required to initiate slip was measured and recorded in each case.</p>',...
    '<p>Due to the curved configuration of the fabric/skin interface, the normal stress distribution between the fabric and skin is not uniform, and the following equation takes account of this.</p>',...
    '<p>$$\\mu _s=\\frac{2}{\\pi }\\left(ln\\left(\\frac{F_s}{m_2.g}\\right)\\right)$$</p>',...
    '<p>This relationship assumes that the fabric is inextensible, and it models the subject''s forearm as a rigid circular cylinder.</p>',...
    '<p>The results of the experiment are plotted in the graph below. A straight line is produced, which goes through the points <b>(',...
    num2str(x1),',&nbsp',num2str(y1),')</b> and <b>(',num2str(x2),',&nbsp',num2str(y2),')</b>.</p>',...
    '<br><img src="@@PLUGINFILE@@/image1.png" style="width:100%%; height:auto;">',...
    '<p><br></p><p>Using the information contained within the question, calculate the value of $$\\mu _s$$ in this case to 3.d.p.</p>',...
    '<p>(Please use this level of accuracy in all calculations within this question)</p>',...
    numString1);

    
generalFeedbackStr = strcat('<p>The equation given in the question can be rearranged to give:</p>',...
        '<p>$$F_s=e^{\\left(\\frac{\\pi }{2}.\\mu _s\\right)}.m_2.g$$</p>',...
        '<br><p>Therefore, if a graph is plotted with $$F_s$$ on the y-axis, and $$m_2.g$$ on the x-axis (as above),',...
        ' then the gradient ($$m$$) of this graph will be equal to:</p><p>$$m=e^{\\left(\\frac{\\pi }{2}\\cdot \\mu _s\\right)}$$</p>',...
        '<br><p>This equation too can be rearranged, and $$\\mu _s$$ is equal to:</p>',...
        '$$\\mu _s=ln\\left(m\\right)\\cdot \\frac{2}{\\pi }$$</p>',...
        '<br><p>Giving a value of $$\\mu _s$$ =&nbsp',num2str((round(us*1000)/1000)),' in this case.</p>');

hint1 = strcat('<b>HINT</b><p>Think of how the information from the gradient of the straight line graph can be used to answer this question.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        plotString1,...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);



