file=fopen('Freefall.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:1
    
ID=strcat(num2str(i));

IDString=strcat('Freefall. Question ID #', ID);
        
    a=-9.81;
    t=0:0.1:100;
    s=a*t;
    d=0.5*a*t*t;
   
% To plot acceleration versus time graph
figure(1)
plot(t,a,'linewidth',3,'Color','red');
hold on
plot(t,s,'linewidth',3,'Color','green');
plot(t,d,'linewidth',3,'Color','blue');
set(gca,'YTickLabel',[],'XTickLabel',[])
%Axes and titles
axis tight
grid on
% title('Acceleration Vs Time','FontSize',14, 'FontWeight','bold');
% ylabel('Acceleration (m/s^2)','Fontsize',12,'FontWeight','bold');
% xlabel('Time (s)','Fontsize',12,'FontWeight','bold');
hold off
%Plot string generation
plotString1= generateImageString(gcf, 'image1');


numString = cloze_numerical((round(B*10)/10), 0.05, 'Good job!', 'Incorrect, try again');

questionString = strcat('<p>A sprinter in a 100 metre race accelerates at a constant rate for the first &nbsp', num2str(D),' metres',...
    ' in &nbsp', num2str(T),' seconds. He then runs at a constant speed. What is his finish time?</p>',...
    '<p>(Give your answer in seconds correct to 1.d.p.)</p>',...
    numString,...
    '<p><img src="http://nrich.maths.org/content/id/7359/track.jpg" alt="" width="362" height="142" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>Using s = (u*t) + 0.5*a*t<sup>2</sup> gives:</p>',...
    '<p>a = &nbsp',num2str(round(A*100)/100),' m/s<sup>2</sup></p>', ...
    '<p>Using v = u + a*t gives:</p>',...
    '<p>v = &nbsp',num2str(round(V*10)/10),' m/s</p>',...
    '<p>The time taken to cover the remaining &nbsp',num2str(C),' metres = &nbsp',num2str(C),'m / &nbsp',num2str(round(V*10)/10),'m/s = &nbsp', num2str(round(U*10)/10),' seconds.</p>', ...
    '<p>Therefore total time = &nbsp',num2str(round(B*10)/10),' seconds.</p>',...
    '<br><p>The acceleration versus time graph for this race will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image2.png" style="width:100%%; height:auto;">',...
    '<br><p>The speed versus time graph is the integral of the acceleration versus time graph, and will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image3.png" style="width:100%%; height:auto;">',...
    '<br><p>The distance versus time graph is the integral of the speed versus time graph, and will look like this:</p><br><p></p><img src="@@PLUGINFILE@@/image4.png" style="width:100%%; height:auto;">');

hint1 = strcat('<p>First of all calculate the initial constant acceleration, then use this to find the final velocity,',...
    ' then the time to cover the last &nbsp',num2str(C),' metres.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        plotString2,...
        plotString3,...
        plotString4);
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
