%Last Updated: 16/09/2015
%Authored By: Avinash Javaji under supervision of Dr. Pilar Garcia Souto
%UCL Department: Medical Physics and Bioengineering

file=fopen('question3.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:1
    
    %Question string joining
    questionString = strcat('Categorise the following partial differential equations: <br><br>', ...
        'The Duhamel method can provide the solution to any inhomogeneous linear PDE, provided that we already know the solution to the corresponding homogenous equation.<br>', ...
        cloze_mcq('vertical', 1, 'true', 'Correct', 'false', 'Incorrect'), ...
        '<br><br>The convolution theorem for Fourier or Laplace transforms allows us to solve nonlinear PDEs analytically.<br>', ...
        cloze_mcq('vertical', 1, 'true', 'Correct', 'false', 'Incorrect'), ...
        '<br><br>The separation-of-variables method can only be used for PDEs defined on finite spatial domains.<br>', ...
        cloze_mcq('vertical', 1, 'true', 'Correct', 'false', 'Incorrect'), ...
        '<br><br>The separation-of-variables method can only be used for homogeneous PDEs.<br>', ...
        cloze_mcq('vertical', 1, 'true', 'Correct', 'false', 'Incorrect'), ...
        '<br><br>The separation-of-variables method can only be used for homogeneous BCs.<br>', ...
        cloze_mcq('vertical', 1, 'true', 'Correct', 'false', 'Incorrect'));
    
    feedbackString = '';
    
    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        'PDEs - True or False', ... 
        questionString, ...
        feedbackString, ...
        '', ...
        '', ...
        '', ...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);