%Last Updated: 15/09/2015
%Authored By: Avinash Javaji under supervision of Dr. Pilar Garcia Souto
%UCL Department: Medical Physics and Bioengineering

file=fopen('question2.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:1
    
    %Embedded components string generation  
    trueOrFalse = 'false';
    mcqString1 = cloze_mcq('drop', 1, ...
        'Hyperbolic', 'Correct', ...
        'Elliptic', '$$ \\small y = \\partial y $$', ...
        'Partially hyperbolic and partially elliptic', 'Incorrect', ... 
        'None of the options', 'Incorrect');
    mcqString2 = cloze_mcq('drop', 1, ...
        'Hyperbolic', 'Correct', ...
        'Partially hyperbolic and partially elliptic', 'Incorrect', ...
        'Partially hyperbolic, partially parabolic and partially elliptic', 'Incorrect', ... 
        'None of the options', 'Incorrect');
    mcqString3 = cloze_mcq('drop', 1, ...
        'Hyperbolic', 'Correct', ...
        'Elliptic', 'Incorrect', ...
        'Parabolic', 'Incorrect', ... 
        'None of the options', 'Incorrect');
    mcqString4 = cloze_mcq('drop', 1, ...
        'Linear homogeneous', 'Correct', ...
        'Nonlinear homogeneous', 'Incorrect', ...
        'Linear inhomogeneous', 'Incorrect', ... 
        'Nonlinear inhomogeneous', 'Incorrect');
    
    %Question string joining
    questionString = strcat('Categorise the following partial differential equations: <br><br>', ...
        '$$ \\small \\frac{\\partial^2 u}{\\partial x^2} = x \\frac{\\partial^2 u}{\\partial t^2} $$ <br><br>', ...
        mcqString1, ...
        '<br><br>$$ \\small y\\frac{\\partial^2 u}{\\partial x^2} + x \\frac{\\partial^2 u}{\\partial x \\partial y} = 0 $$ <br><br>', ...
        mcqString2, ...
        '<br><br>$$ \\small (1+ y) \\frac{\\partial^2 u}{\\partial x^2} + (1 + 2y) \\frac{\\partial^2 u}{\\partial x \\partial y} + 4y \\frac{\\partial^2 u}{\\partial y^2} = 0 $$ <br><br>', ...
        mcqString3, ...
        '<br><br>$$ \\small (1+ y) \\frac{\\partial^2 u}{\\partial x^2} + (1 + 2y) \\frac{\\partial^2 u}{\\partial x \\partial y} + 4y \\frac{\\partial^2 u}{\\partial y^2} = 0 $$ <br><br>', ...
        mcqString4);
    
    feedbackString = '';
    
    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        'PDEs - Terminology', ... 
        questionString, ...
        feedbackString, ...
        '', ...
        '', ...
        '', ...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);