file=fopen('Amontons.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:1
    
ID=strcat(num2str(i));

IDString=strcat('Amontons. Question ID #', ID);

m=randi([1688,2193])/1000;
us=(log(m))*2/pi;
x1=randi([10,20]);
y1=m*x1+10;
x2=randi([70,90]);
y2=m*x2+10;

% To plot  graph
figure(1)
plot([x1,x2],[y1,y2],'linewidth',2,'Color','red');
hold on
%Axes and titles
axis([0 x2+10 0 y2+10])
grid minor
grid on
title('Friction Between Fabric and Skin','FontSize',14, 'FontWeight','bold');
ylabel('Force (mN)','Fontsize',12,'FontWeight','bold');
xlabel('m_{2}.(g)','Fontsize',12,'FontWeight','bold');
hold off
%Plot string generation
plotString1= generateImageString(gcf, 'image1');

numString1 = cloze_numerical((round(us*1000)/10000), 0.0005, 'Good job!', 'Incorrect, try again');

questionString = strcat('Amontons'' law states that the force needed to initiate slip between two surfaces ($$F_s$$), i.e. to overcome static friction, is a fixed proportion of the normal force ($$N$$),',...
    'between the two surfaces, and these two parameters are related by the coefficient of static friction ($$\\mu _s$$), as follows:',...
    '<p>$$\\mu _s=\\frac{F_s}{N}$$',...
    '<p>An experiment was carried out as per the diagram below, where a weight of mass m2 was suspended over a subject''s forearm by a section of nonwoven fabric',...
    '<p>The mass of the weight was varied, and the force required to initiate slip was measured and recorded in each case.</p>',...
    '<p>Due to the curved configuration of the fabric/skin interface, the normal stress distribution between the fabric and skin is not uniform, and the following equation takes account of this.</p>',...
    '<p>$$\\mu _s=\\frac{2}{\pi }\\left(ln\\left(\\frac{F_s}{m_2.g}\\right)\\right)$$</p>',...
    '<p>This relationship assumes that the fabric is inextensible, and it models the subject''s forearm as a rigid circular cylinder.</p>',...
    '<p>The results of the experiment are plotted in the graph below. A straight line is produced, which goes through the points (',...
    num2str(x1),',',num2str(y1),') and (',num2str(x2),',',num2str(y2),').</p>',...
    '<p>Using the information contained within the question, calculate the value of $$\\mu _s$$ in this case to 3.d.p.</p>',...
    '<p>Use a 
    
generalFeedbackStr = strcat('In order to find the crack length at failure, rearrange the Griffiths Formula to make $$l$$ the subject as follows:',...
    '<p>$$l=\\left(\\left(\\frac{\\sigma \\:_c}{\\sigma \\:_o}-1\\right)\\cdot \\:0.5\\right)^2\\cdot r$$</p>',...
    '<p>In this case: $$\\small\\sigma _c$$ = &nbsp',num2str(fs),' MPa; $$\\small\\sigma _o$$ = &nbsp',num2str(ns),' MPa; and $$r$$ =&nbsp',num2str(r),'$$\\small\\mu$$m</p>',...
    '<p></p><br><p>By rearranging the equation given in the question, and integrating between the limits of the initial crack length $$(_{a_i})$$ and crack length at failure $$(_{a_f})$$, the following expression can be produced:</p>',...
    '<p>$$N=C\\cdot \\left(\\Delta \\sigma _o\\right)^2\\cdot \\pi ^2\\cdot \\left[-a^{-1}\\right]_{a_i}^{a_f}$$</p>',...
    '<p>In this case: $$C$$ = 3 x 10<sup>-16</sup> Pa<sup>-2</sup>.m<sup>-1</sup>; $$\\small\\Delta \\sigma _o$$ =&nbsp',num2str(ns),' MPa; $$_{a_f}$$ =&nbsp',num2str(round(af*10)/10),' mm; and $$_{a_i}$$ =&nbsp',num2str(ai),' mm.</p>',...
    '<p>This gives a value of $$N$$ =&nbsp',num2str(round(N)),' (the number of steps before the plate fails).</p>');

hint1 = strcat('<p>Use the Griffiths Formula (or Stress Raiser equation) to answer the first part of the question:</p>',...
    '<p>$$\\sigma _c=\\sigma _o\\cdot \\left(1+2\\cdot \\sqrt{\\frac{l}{r}}\\right)$$</p>',...
    '<p>Where: $$\\small\\sigma _c$$ = the stress at the tip of the crack; $$\\small\\sigma _o$$ = the nominal stress distant from the crack;',...
    ' $$l$$ = the the length of the surface crack; and $$r$$ = the crack tip radius.</p>',...
    '<p>To answer the second part of the question, you will need to integrate the equation given in the question, and evaluate it between the limits of the inital crack length, and crack length at plate failure.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);



