file=fopen('Fridge.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Fridge. Question ID #', ID);

% assigning random variables

       d=randi([10,20]);
       m=randi([300,600])/10;
       mu=randi([5,15])/10;
       t=randi([10,20]);
       g=9.8;

%      calculations
       F=m*mu*g;
       W=d*F;
       p=W/t;
       
numString1 = cloze_numerical((round(F*10)/10), 0.02*F, 'Good job!', 'Incorrect, try again');        
numString2 = cloze_numerical((round(W*10)/10), 0.02*W, 'Good job!', 'Incorrect, try again');
numString3 = cloze_numerical((round(p*10)/10), 0.02*p, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A man pushes a&nbsp',num2str(m),' kg fridge at a constant speed over a distance of&nbsp',num2str(d),' m across a level floor, in a time of&nbsp',num2str(t),' s.',...
        ' The kinetic coefficient of friction is&nbsp',num2str(mu),'.</p>',...
        '<p><br></p><p><img src="http://s28.postimg.org/ejr8ra799/fridge.jpg" alt="" width="420" height="394" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
        '<p>Assume a value of $$g$$ = -9.8m/s<sup>2</sup> for the purposes of this question.</p>',...
        '<br><p>With what force, $$F$$, is the man pushing the fridge?</p>',...
        '<p>',numString1,' N',....
        '<p>How much work has he done in those 20 seconds?</p>',...
        '<p>',numString2,' J',....
        '<p>At what power level does he transfer energy to the fridge?</p>',...
        '<p>',numString3,' W',....
        '<p>(Please give your answers correct to 1.d.p.)</p>',...
        '<p>(Question ID #',num2str(i),').</p>');
        

generalFeedbackStr = strcat('<p>As the fridge is travelling at a constant speed, it has zero acceleration, and therefore the forces acting on it are balanced.</p>',...
    '<p>This means that $$F$$ is equal to the frictional force between the ground and the fridge:</p>',...
    '<p>$$F=\\mu.m.g=',num2str(round(F*10)/10),'N$$</p>',...
    '<p>Where $$\\mu$$ is the kinetic coefficient of friction, $$m$$ is the mass of the fridge, and $$g$$ is the gravitational constant as given above.</p>',...
    '<br><p>Remembering that work, $$W$$, is equal to the force, $$F$$, applied to a load, multiplied by the displacement, $$x$$, of the the load in the direction of the force:</p>',...
    '<p>$$W=F.x=',num2str(round(W*10)/10),'J$$</p>',...
    '<br><p>Power, $$P$$ is the amount of work, $$W$$, performed in a given time, $$t$$:</p>',...
    '<p>$$P=\\frac{W}{t}=',num2str(round(p*10)/10),'W$$</p>',...
'<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from ''http://book.transtutors.com/qimage/image09042014050.png''</p>');

 hint1 = strcat('<b>HINT</b><p>Remember that as the fridge is travelling as a constant speed, it has zero acceleration, and therefore the forces acting on it are balanced.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
