file=fopen('DavidVsGoliath.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('DavidVsGoliath. Question ID #', ID);

% assigning random variables
       l=randi([70,140])/100;
       t=randi([5,15])/10;
       a=randi([10,20]);
       
% calculations
    w=a*t;
    v=l*w;
    v1=3.6*v;
           
numString1 = cloze_numerical((round(v*10)/10), 0.05, 'Good job!', 'Incorrect, try again');

questionString = strcat('<p>David is fighting Goliath. If David''s&nbsp',num2str(l),' m slingshot is accelerated for&nbsp',num2str(t),' s at&nbsp',num2str(a),' rad/s<sup>2</sup>, what will be the initial linear velocity of the projected stone as it leaves the slingshot?</p>',...
    '<br><p><img src="http://s8.postimg.org/vobi0cig5/image.jpg" alt="" width="470" height="429" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
    '<p>(Please give your answer correct to 1.d.p)</p>',...
    numString1, ' m/s',...
    '<p>(Question ID #',num2str(i),')');

generalFeedbackStr = strcat('First of all we need to calculate the stone''s angular velocity at the moment it leaves the slingshot, using one of the equations from the previous question:</p>',...
    '<p>$$\\small\\omega=\\alpha\\cdot t=',num2str(a),'\\time ',num2str(t),'=',num2str(round(w*10)/10),'$$ rad/s.</p>',...
    '<br><p>Next, we need to convert this angular velocity into linear velocity using the relationship $$V=r\\cdot \\omega$$, where $$V$$ is linear velocity in m/s,',...
    ' $$r$$ is radius in m, and $$\\small\\omega$$ is angular velocity, in rad/s.</p>',...
    '<br><p>Applying this equation to this question gives,</p>',...
    '<p>$$V=',num2str(l),'\\times ',num2str(round(w*10)/10),'=',num2str(round(v*10)/10),'$$ m/s.</p>',...
    '<br><p>This is equivalent to&nbsp',num2str(round(v1)),' km/h!',...
     '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from Dynamics lecture notes.</p>');

    hint1 = strcat('<b>HINT</b><p>Calculate the stone''s angular velocity, and then convert this to linear velocity.</p>');...

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
