    file=fopen('Angular-Acceleration.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Angular-Acceleration. Question ID #', ID);
    
        
    B=randi([1,10]);
    A=randi([-10,-1]);
    T=randi([1,10]);
    C=3*A;
    D=2*B;
    E=2*C;
    AV=(3*A*T*T)+(2*B*T);
    ANS=(E*T)+D;

numString = cloze_numerical(ANS, 0.5, 'Good job!', 'Incorrect, try again');

questionString = strcat('<p>The angular position, $$\\theta$$, of an orbiting object can be described by:</p><p>$$\\theta=',num2str(A),'.t^3+',num2str(B),'.t^2$$</p><p>Where $$t$$ is time in seconds.</p>',... 
    '<p>What is the angular acceleration at $$t$$ = &nbsp',num2str(T),' s.</p>',...
    '<p><img src="http://s14.postimg.org/taxibfmg1/formula_for_angular_accelerations.png" alt="" width="215" height="254" /></p><br>',...
    '<p>Give your answer in rad/s<sup>2</sup>, to the nearest whole number.</p>',...
    numString,...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>By differentiating with respect to time, and substituting in $$t$$ = &nbsp',num2str(T),' s:</p><p>Angular velocity $$=\\omega=\\frac{d\\theta }{dt}=(3\\times ',num2str(A),'\\times t^2)+(2\\times ',num2str(B),'\\times t)=',num2str(AV),'$$ rad/s.</p>',...
        '<p>Angular acceleration $$=\\alpha=\\frac{d\\omega }{dt}=(2\\times',num2str(3*A),'\\times t)+',num2str(D),'=', num2str(ANS),'$$ rad/s<sup>2</sup>.</p>',...
    '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from ''http://images.tutorvista.com/cms/formulaimages/83/formula-for-angular-accelerations.PNG''</p>');
  
    
    hint1 = strcat('<b>HINT</b><p>Use your knowledge that angular velocity is the differential of angular displacement with respect to time, and that angular acceleration is the differential of angular velocity with respect to time, to answer this question.</p>');...

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);