%Last Updated: 17/09/2015
%Created By: Avinash Javaji under supervision of Dr. Pilar Garcia Souto
%UCL Department: Medical Physics and Bioengineering

file=fopen('question6.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
    %Calculations
    mu = randi([2,10]);
    sig = randi([1,4]);
    limit_min = randi([mu-6,mu-1]);
    limit_max = randi([(mu+1),(mu+6)]);
    
    %syms f sig x
    f = @(x) (exp( ((x-mu)/sig).^2 / (-2) )) / ((2*pi*sig).^0.5);
    p_ans = integral(f,limit_min,limit_max);
    syms f_to_disp si x muu
    f_to_disp = (exp( ((x-muu)/si).^2 / (-2) )) / ((2*pi*si)^0.5);
    latex_str = strrep(strrep(strrep(latex(f_to_disp), 'muu','\mu'), 'si', '\sigma'),'\','\\');
    
    %fprintf('N: %d, mean: %d, s: %d, fromVal: %d, toVal: %d', n, mean, s, fromVal, toVal);
    
    %Embedded components string generation
    numStringP1 = cloze_numerical(p_ans, 0.01, 'Good job!', 'Incorrect, try again', 3, 6);
    numStringP2 = cloze_numerical(0.68, 0.01, 'Good job!', 'Incorrect, try again', 3, 6);
    numStringP3 = cloze_numerical(0.955, 0.01, 'Good job!', 'Incorrect, try again', 3, 6);
    numStringP4 = cloze_numerical(0.997, 0.01, 'Good job!', 'Incorrect, try again', 3, 6);
    
    %Question string joining
    questionString = strcat( ...
        'Consider a normal distribution with &mu; =&nbsp;', num2str(mu), ' and &sigma; =&nbsp;', num2str(sig), '.&nbsp;', ...
        'Calculate the following probabilities:', ...
        '<br><br>The random variable X is located between&nbsp;', num2str(limit_min), '&nbsp;and&nbsp;', num2str(limit_max), ', namely P(', num2str(limit_min), '&nbsp;&le;&nbsp;X&nbsp;&le;&nbsp;', num2str(limit_max), '):', ...
        '<br>', numStringP1, ...
        '<br><br>P(&mu;&nbsp;-&nbsp;&sigma;&nbsp;&le;&nbsp;X&nbsp;&le;&nbsp;&mu;&nbsp;+&nbsp;&sigma;)', ...
        '<br>', numStringP2, ...
        '<br><br>P(&mu;&nbsp;-&nbsp;2&sigma;&nbsp;&le;&nbsp;X&nbsp;&le;&nbsp;&mu;&nbsp;+2&nbsp;&sigma;)', ...
        '<br>', numStringP3, ...
        '<br><br>P(&mu;&nbsp;-&nbsp;3&sigma;&nbsp;&le;&nbsp;X&nbsp;&le;&nbsp;&mu;&nbsp;+3&nbsp;&sigma;)', ...
        '<br>', numStringP4, ...
        '<p style="font-size: 0px">$$</p>' ... This causes the latex to be non-image, hence much clearer
    );

    feedbackString = strcat( ...
        'The normal distribution is given by:<br>', ...
        '<span style="text-align:center">$$ \\LARGE ', latex_str, ' $$</span><br><br>', ...
        'The probability that the random variable X is located between a and b is:<br>', ...
        '<span style="text-align:center">$$ P(a \\leq X \\leq b) = \\int_{a}^{b} f(x)dx $$</span><br><br>', ...
        'Use matlab to solve the integrals.<br>',...
        '$$ P(', num2str(limit_min), ' \\leq X \\leq ', num2str(limit_max), ') = ', sprintf('%0.3f', p_ans), ' $$<br><br>',...
        'However in general,<br>', ...
        '$$ P(\\mu - \\sigma \\leq X \\leq \\mu + \\sigma) \\approx 0.68 $$<br>', ...
        '$$ P(\\mu - 2\\sigma \\leq X \\leq \\mu + 2\\sigma) \\approx 0.955 $$<br>', ...
        '$$ P(\\mu - 3\\sigma \\leq X \\leq \\mu + 3\\sigma) \\approx 0.997 $$<br>', ...
        '<p style="font-size: 0px">$$</p>' ... This causes the latex to be non-image, hence much clearer
    );
    
    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        'Descrete Stats Q3', ... 
        questionString, ...
        feedbackString, ...
        '', ...
        '', ...
        '', ...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);