file=fopen('Thermal-Expansion-Advanced.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100

ID=strcat(num2str(i));

IDString=strcat('Thermal-Expansion-Avanced. Question ID #', ID);

w=randi([3,8]);
h=w;
tc=randi([60,80]);
tb=37;
dt=tc-tb;
dct=w*(1+(dt*8/1000000));
dca=w*(1+(dt*25/1000000));
a=h/2;
b=((dct*dca)*((a*55)+20))/((a*55*dct)+(20*dca));
strain=(b-dct)/dct;
stress=20*strain;
answer=stress*1000;
answer=round(answer*10)/10;

% rectangle('Position',[0 0 w+2 w+2],'FaceColor','y','EdgeColor','k')
% hold on
% rectangle('Position',[1 1 w w],'FaceColor',[0.4,0.4,0.4],'EdgeColor',[0.4,0.4,0.4])
% axis([0 w+2 0 w+2])
% % set(gca,'YTickLabel',[],'XTickLabel',[])
% hold off

% correct = strcat('<p><img src="http://s27.postimg.org/5mmvlftir/correct.jpg" alt="" width="321" height="63" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>');

numString1 = cloze_numerical(answer, 0.005, 'Good Job!', 'Incorrect');

questionString = strcat('<p>A man has a major filling to one of his molars due to decay. The filling is a square of side&nbsp',num2str(w),'mm.</p>',...
    '<p>Suppose the filling is a perfect fit in the cavity at body temperature (that is, neither the tooth nor the filling material is in tension or compression),',...
    ' what stress would be induced in the tooth if the filling were now uniformly heated to the hot coffee temperature of&nbsp',num2str(tc),' <sup>o</sup>C?</p>',...
    '<p>The remaining tooth (yellow) is 1mm thick to the sides of the filling (grey), as below; that is it has outside dimensions of&nbsp',num2str(w+2),' x&nbsp',num2str(w+2),' mm.',...
    ' The tooth and amalgam materials have coefficients of thermal expansion of 8 x 10<sup>-6</sup>K<sup>-1</sup> and 25 x 10<sup>-6</sup>K<sup>-1</sup>, respectively,',...
    ' and their respective elastic moduli are 20 GPa and 55 GPa. Body temperature is 37 <sup>o</sup>C.</p>',...
    '<p>(Give your answer in MPa correct to 1.d.p)</p>',...
    '<br><img src="http://s4.postimg.org/9jaxuqkdp/image.jpg" alt="" width="363" height="363" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><p><br></p>',...
    numString1,' MPa',...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>Suppose that one of the sides of the square filling expands to X<sub>',num2str(tc),'</sub> at&nbsp',num2str(tc),'<sup>o</sup>C.',...
    ' Also suppose that if the tooth cavity and amalgam filling were unconstrained by one another that their X<sub>',num2str(tc),'</sub> dimensions would be X<sub>',num2str(tc),'t</sub> and X<sub>',num2str(tc),'a</sub>. Then:</p>',...
    '<p>X<sub>',num2str(tc),'t</sub> =&nbsp',num2str(w),'(1+(',num2str(dt),'x8x10<sup>-6</sup>))mm =&nbsp',num2str(dct),' mm.</p>',...
    '<p>X<sub>',num2str(tc),'a</sub> =&nbsp',num2str(w),'(1+(',num2str(dt),'x25x10<sup>-6</sup>))mm =&nbsp',num2str(dca),' mm.</p>',...
    'Without constraint therefore, the amalgam dimensions would be&nbsp',num2str(dca-dct),'mm larger than the tooth. In practice, they are constrained to have the same dimensions.',...
    ' When this happens, the compressive force in the amalgam will be balanced by the tensile force in the tooth. If the stresses in the two materials are $$\\sigma _a$$ and $$\\sigma _t$$,',...
    ' then:</p><p>$$2.\\sigma _t=',num2str(h),'.\\sigma _a$$</p>',...
    'because the widths of the materials perpendicular to the stresses being considered are ~2mm and&nbsp~',num2str(h),'mm, so $$\\sigma _a$$ acts over&nbsp',num2str(h/2),' times the area of $$\\sigma _t$$.</p>',...
    '<p>The strains, $$\\epsilon _t$$ and $$\\epsilon _a$$, accompanying these stresses are:</p><br>',...
    '<p>$$\\epsilon _t=(X_{',num2str(tc),'}-X_{',num2str(tc),'t})/X_{',num2str(tc),'t}$$</p>',...
    '<p>$$\\epsilon _a=(X_{',num2str(tc),'a}-X_{',num2str(tc),'})/X_{',num2str(tc),'a}$$</p>',...
    '<br><p>If the moduli of the materials are $$E_t$$ and $$E_a$$, combining the previous three equations will give:</p><br>',...
    '<p>$$\\frac{(X_{',num2str(tc),'}-X_{',num2str(tc),'t}) }{X_{',num2str(tc),'t} }\\cdot E_t=',num2str(a),'\\cdot \\frac{(X_{',num2str(tc),'a}-X_{',num2str(tc),'}) }{X_{',num2str(tc),'a} }\\cdot E_a$$</p>',...
    '<br><p>Therefore:</p><br>',...
    '<p>$$(X_{',num2str(tc),'}-X_{',num2str(tc),'t})\\cdot E_t\\cdot X_{',num2str(tc),'a}=',num2str(a),'\\cdot (X_{',num2str(tc),'a}-X_{',num2str(tc),'})\\cdot E_a\\cdot X_{',num2str(tc),'t}$$</p>',...
    '<br><p>Therefore:</p><br>',...
    '<p>$$X_{',num2str(tc),'}\\cdot (E_t\\cdot X_{',num2str(tc),'a}+',num2str(a),'\\cdot E_a\\cdot X_{',num2str(tc),'t})=',num2str(a),'\\cdot X_{',num2str(tc),'a}\\cdot X_{',num2str(tc),'t}\\cdot E_a+X_{',num2str(tc),'t}\\cdot X_{',num2str(tc),'a}\\cdot E_t$$</p>',...
    '<br><p>Therefore:</p><br>',...
    '<p>$$X_{',num2str(tc),'}=\\frac{X_{',num2str(tc),'a}\\cdot X_{',num2str(tc),'t}\\cdot (',num2str(a),'\\cdot E_a+E_t) }{',num2str(a),'\\cdot E_a\\cdot X_{',num2str(tc),'t}+E_t\\cdot X_{',num2str(tc),'a} }$$</p>',...
    '<br><p>Entering values for $$E_a$$ and $$E_t$$ from the question, and for $$X_{',num2str(tc),'a}$$ and $$X_{',num2str(tc),'t}$$ as calculated above:</p><br>',...
    '<p>$$X_{',num2str(tc),'}=\\frac{(',num2str(dca),'\\times ',num2str(dct),')((',num2str(a),'\\times 55)+20) }{(',num2str(a),'\\times ',num2str(dct),')+(20\\times ',num2str(dca),') }=',num2str(b),'mm$$</p>',...
    '<br><p>The strain in the tooth therefore is (',num2str(b),' -&nbsp',num2str(dct),') /&nbsp',num2str(dct),' =&nbsp',num2str(strain),'</p>',...
    '<p>Therefore:</p>',...
    '<p>$$\\sigma _t$$ = 20 x&nbsp',num2str(strain),' GPa ',...
    ' = 20 x&nbsp',num2str(strain*1000),' MPa ',...
    ' =&nbsp<b><u>',num2str(answer),' MPa</b></u></p>',...
    '<p>The stress in the tooth would be the same across the length and breadth of the filling, as the filling is square, with an equal amount of tooth bordering each edge of the filling.</p>',...
    '<p>Although&nbsp',num2str(answer),' MPa is less than the 40 MPa fracture strength of the tooth, it wouldn''t take a very severe stress concentrator to bridge the gap and precipitate failure.</p><br>',...
    '<p>Similarly, if you eat cold ice cream the amlagam wants to contract more than its host cavity. This leads to cyclic loading as the temperature of ',...
    ' your tooth and its filling rise and fall according to what you eat. And this can encourage the formation of cracks at either the amalgam/tooth interface or ',...
    ' in the tooth as it is forced by the filling to expand more than it wishes, so acquiring tensile forces. Trying to match the coefficient of expansion ',...
    ' of natural tooth is one of the targets of those developing new resin cavity fillers.</p>' );
        
hint1 = strcat('<b>HINT</b><p>Calculate how big the cavity would be in the absence of the filling, and how big the filling would be if unconstrained by the tooth.</p>',...
    '<p>Next, work out how much the cavity would need to be stretched and the filling contracted to match in size, given that the net force in any direction must be zero.</p>',...
    '<p>Finally, work out the associated strain and using the moduli, work out the associated stress.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
 
end
    
fprintf(file, quiz_end()); %xml closing code
fclose(file);


