file=fopen('Angle repose.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Angle repose. Question ID #', ID);

% assigning random variables

       mu=randi([100,200])/100;
       
%      calculations
      theta=atand(mu);
           
numString1 = cloze_numerical((round(theta*10)/10), 0.05, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>The coefficient of friction, $$\\mu$$, between a load of sand and the bed of a dump truck in which it is carried is&nbsp',num2str(mu),'.</p>',...
        '<p>At what angle to the horizontal, $$\\alpha$$, does the truck bed have to be tilted before the sand starts to slide out?</p>',...
        '<br><p><img src="http://s4.postimg.org/xhyx4nf3x/What_s_the_angle_of_repose_geograph_org_uk.jpg" alt="" width="640" height="480" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
        '<p>$$\\alpha$$ =&nbsp',numString1,' degrees.',...
        '<p>(Please give your answer correct to 1.d.p.)</p>',...
        '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>The force diagram below will be useful when answering this question:</p>',...
            '<br><p><img src="http://s23.postimg.org/67quom2rv/image2.jpg" alt="" width="348" height="231" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
            '<p>Just before the sand slides, we know that it is in equilibirum, i.e. $$F=m.g.sin\\alpha $$.</p>',...
            '<p>We also know that $$F=\\mu .R=\\mu .m.g.cos\\alpha $$.</p>',...
            '<p>From this we can develop the expression:</p>',...
            '<p>$$m.g.sin\\alpha =\\mu .m.g.cos\\alpha $$</p>',...
            '<p>Which can be simplified to:</p>',...
            '<p>$$\\frac{sin\\alpha }{cos\\alpha }=tan\\alpha =\\mu $$</p>',...
            '<p>Therefore:</p>',...
            '<p>$$\\alpha =\\arctan \\left(\\mu \\right)=',num2str(round(theta*10)/10),'$$ degrees.</p>',...
            '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
            '<p>Image 1 adapted from ''https://upload.wikimedia.org/wikipedia/commons/7/77/What''s_the_angle_of_repose%%5E_-_geograph.org.uk_-_1164470.jpg''</p>',...
            '<p>Image 2 adapted from ''http://s3.mnimgs.com/img/shared/discuss_editlive/5057757/2013_09_03_07_18_43/image3142284526248846124.jpg''</p>');
        
    hint1 = strcat('<b>HINT</b><p>Start off by drawing a force diagram showing: the weight of the load, the frictional force between the load and the truck, and the reaction force that the truck provides.</p><p>The frictional force will be equal to the component of the weight of the load down the truck bed, when the load starts to slide out.</p>');...

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
