file=fopen('Golf club.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Golf club. Question ID #', ID);

% assigning random variables

       l=randi([70,100])/100;
       a=randi([10,20])/10;
       
%      calculations
      v1=a*l;
      v1=round(v1*10)/10;
      v2=v1*180/pi;

           
numString1 = cloze_numerical((round(v1*10)/10), 0.05, 'Good job!', 'Incorrect, try again');
numString2 = cloze_numerical((round(v2*10)/10), 0.05, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A golf club is swung with an average angular acceleration, $$\\small\\alpha$$, of&nbsp',num2str(a),' rad.s<sup>-2</sup>.</p>',...
        '<p>What is the angular velocity, $$\\small\\omega$$, (in both degree and radian based units) of the club when it strikes the ball at the end of a&nbsp',num2str(l),' seconds swing?</p>',...
        '<br><p><img src="http://s8.postimg.org/p8iinbpph/physics_golf_swing_1.png" alt="" width="330" height="444" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
        numString1,' rad/s<p>',...
        numString2,' degree/s',...
        '<p>(Give your answers correct to 1.d.p, and use your rounded answer from the first part of the question to answer the second part of the question)</p><p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>It may be helpful to recall the following concepts regarding angular motion over time, $$t$$:</p>',...
        '<p>Angular displacement, $$\\small\\theta=\\omega\\cdot t$$</p>',...
        '<p>Angular velocity, $$\\small\\omega=\\frac{d\\theta }{dt}=\\alpha\\cdot t$$</p>',...
        '<p>Angular acceleration, $$\\small\\alpha=\\frac{d^2\\theta }{dt^2}=\\frac{d\\omega }{dt}$$</p>',...
        '<p>These parameters can be measured in either rad or degree based units, where,</p><p>1 rad = $$\\small(\\frac{180}{\\pi })$$ degrees, and</p><p>1 degree = $$\\small(\\frac{\\pi}{\\180 })$$ rad.</p>',...
        '<br><p>Therefore, in the case of this question, applying $$\\small\\omega=\\alpha\\cdot t$$ gives:</p>',...
        '<p>$$\\small\\omega=',num2str(a),'\\time ',num2str(l),'=',num2str(v1),'$$ rad/s</p>',...
        '<p>Multiplying by $$\\small(\\frac{180}{\\pi })$$ gives:</p><p>$$\\small\\omega=',num2str(round(v2*10)/10),'$$ degrees/s</p>',...
        '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
        '<p>Image adapted from ''http://www.wickedstick.com/wp-content/uploads/2013/01/physics_golf_swing_1-222x300.png''</p>');
   
    hint1 = strcat('<b>HINT</b><p>Remember that angular velocity, $$\\small\\omega$$, is the rate of change of angular displacement with respect to time.</p><p>Remember also that angular acceleration, $$\\small\\alpha$$, is the rate of change of angular velocity with respect to time.</p>');...

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
