file=fopen('Merry Go Round.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100
    
ID=strcat(num2str(i));

IDString=strcat('Merry Go Round. Question ID #', ID);

% assigning random variables

       r=randi([10,30])/10;
       mu=randi([50,150])/100;
       g=9.8;
%      calculations
       w=sqrt((mu*g)/r);
           
numString1 = cloze_numerical((round(w*10)/10), 0.05, 'Good job!', 'Incorrect, try again');


questionString = strcat('<p>A child stands&nbsp',num2str(r),'m from the axis of a rotating merry-go-round.',...
    ' The coefficient of friction between her shoes and the platform is&nbsp',num2str(mu),'.</p>',...
    '<p>What is the maximum angular velocity, $$\\omega$$, of the merry-go-round if she is not to start slipping outwards?</p>',...
    '<br><p><img src="http://s23.postimg.org/3ypnmwxnf/689.jpg" alt="" width="314" height="226" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p><p><br></p>',...
    '<p>Assume a value of $$g$$ = -9.8m/s<sup>2</sup> for the purposes of this question.</p>',...
    '<br><p>$$\\omega\\$$ =&nbsp',numString1,' rad/s.</p>',...
    '<p>(Please give your answer correct to 1.d.p.)</p>',...
    '<p>(Question ID #',num2str(i),').</p>');

generalFeedbackStr = strcat('<p>The frictional force, $$F_f$$,  experienced preventing the child from slipping outwards can be expressed as:</p>',...
    '<p>$$F_f=\\mu .R=\\mu .M.g$$',...
    '<p>Where $$\\mu$$ is the coefficient of friction as given above, $$R$$ is the reaction force between her shoes and the platform, ',...
    ' $$M$$ is the child''s mass, and $$g$$ is the gravitational constant, as given above.</p>',...
    '<br><p>The centripetal force, $$F_c$$, experienced by the child can be expressed as:</p>',...
    '<p>$$F_c=M.a_c=M.r.\\omega ^2$$',...
    '<p>Where $$r$$ is the distance between the child and the centre of the merry-go-round, and $$a_c$$ is the centripetal acceleration.</p>',...
    '<br><p>At maximum velocity whilst the child is not slipping outwards, these two forces will be balanced. Therefore, equating and simplifying these two expressions gives:</p>',...
    '<p>$$\\mu .g=r.\\omega ^2$$</p>',...
    '<p>Therefore:</p>',...
    '<p>$$\\omega =\\sqrt{\\frac{\\mu .g}{r}}=',num2str(round(w*10)/10),'$$ rad/s.</p>',...
 '<p>---------------------------------------------------------------------------------------------------------------------</p>',...
     '<p>Image adapted from ''http://minerva.union.edu/labrakes/Phy110_E3_Solution_F11.pdf''</p>');   
    hint1 = strcat('<b>HINT</b><p>Develop expressions for both the frictional force and the centripetal force experienced by the child.</p><p>Remember that these will be balanced, when $$\\omega$$ is at a maximum whilst the child is not slipping outwards.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
    
end
fprintf(file, quiz_end()); %xml closing code
fclose(file);
