file=fopen('Shear Strain.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code

for i=1:1:100

ID=strcat(num2str(i));

IDString=strcat('Shear Strain. Question ID #', ID);

L=randi([45,55]);
r=randi([20,40])/10;
theta=randi([25,75])/10;
strain=(pi*theta*r)/(180*L);
strain=strain*1000;
strain=round(strain*100)/100;
E=randi([20,40])/10;
dr=0.5*r;
Lm=L/100;
rm=r/100;
drm=dr/100;
EG=E*10^9;
rdr=rm-drm;
A=((pi)^3*EG)/Lm;
B=(theta/180)^2;
C=(rm^4)/4;
D=(rdr^4)/4;
W=A*B*(C-D);
W=round(W*100)/100;


correct = strcat('<p><img src="http://s27.postimg.org/5mmvlftir/correct.jpg" alt="" width="321" height="63" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>');
image1 = strcat('<p><img src="http://s27.postimg.org/pva975stv/wrong1.jpg" alt="" width="339" height="61" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>');
image2 = strcat('<p><img src="http://s27.postimg.org/w6fgnku2b/wrong2.jpg" alt="" width="351" height="64" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>');
image3 = strcat('<p><img src="http://s14.postimg.org/bgcffx675/wrong3.jpg" alt="" width="320" height="63" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive"><br></p>');

numString1 = cloze_numerical(strain, 0.005, 'Good Job!', 'Incorrect');
numString2 = cloze_mcq('vertical', 1, correct, 'Good Job!', image1, 'Incorrect',image2, 'Incorrect', image3,'Incorrect');
numString3 = cloze_numerical(W, 0.005, 'Good Job!', 'Incorrect');

questionString = strcat('<p>Two sportsmen collide resulting in the femur of one being loaded in torsion, as indicated below, ',...
    ' which shows the affected bone modelled as a hollow cylinder. The top surface of the cylinder has been rotated by $$\\small\\theta$$ =&nbsp',num2str(theta),'<sup>o</sup>',...
    ' relative to the bottom surface, so that the line AB in the unstrained bone has become AB<sup>I</sup>.</p>',...
    '<img src="http://s4.postimg.org/6kvvea6fh/image.jpg" alt="" width="560" height="373" role="presentation" style="vertical-align:middle; margin: 0 .5em;" class="img-responsive">',...
    '<p><br></p><p>This figure shows a cylindrical bone loaded in torsion as indicated by the arrows (left). The length of the bone, <i>L</i>, is&nbsp',num2str(L/100),' m.  On the right, the top surface of the bone is shown, in which the darkly shaded annulus',...
    ' is the end of a cylindrical element of radius, <i>r</i>, and wall thickness, <i>dr</i>.</p>',...
    '<p><b>Part A</b></p><p>What is the shear strain ($$\\small\\epsilon$$) in the bone at a distance <i>r</i> cm from the femur axis?</p>',...
    '<p>(Please give your answer correct to 2.d.p)</p>',...
    numString1,' x10<sup>-3</sup>',...
    '<p><b>Part B</b></p><p>Assuming that deformation throughout the bone is elastic, which of the following equations correctly describes the strain energy, <i>dW</i>, stored in the ',...
    ' bone, which has a shear modulus of <i>E</i>.',...
    numString2,...
    '<p><b>Part C</b></p><p>Solve this differential equation to calculate the total strain energy stored in the bone, if <i>E</i> has a value of&nbsp',num2str(E),' GPa, and the bone has an outer radius, <i>r<sub>o</sub></i>, of &nbsp',num2str(r/100),' m and a wall thickness, <i>t</i>, of &nbsp',num2str(dr/100),' m.<p>',...
    '<p>(Please give your answer correct to 2.d.p)</p>',...
    numString3,' Joules');

generalFeedbackStr = strcat('<p><b>Part A</b></p><p>To calculate the shear strain ($$\\epsilon$$) we must first calculate the extension.</p>',...
        'This is equal to the circumference of a circle of radius <i>r</i> ($$2\\pi r$$), multiplied by the number of shear revolutions occuring ($$\\frac{\\theta }{360}$$).</p>',...
        'As strain is simply a ratio of extension to original length, the extension is divided by <i>L</i>. The resulting expression can be simplified to give:</p>',...
        '<br><p> $$\\epsilon =\\frac{\\pi .r.\\theta }{180.L}$$</p>',...
        '<br><b><p>Part B</b></p><p>Assuming that deformation is elastic throughout, the shear stress at any point will be given by the expression ($$E.\\epsilon$$).</p>',...
        '<p>The amount of energy stored per unit volume of bone is equal to the integral of the stress/strain plot between the limits of the bone''s unstrained position and strained positions, as follows:</p>',...
        '<br><p>$$\\int _0^{\\epsilon }\\left(E.\\epsilon \\right).d\\epsilon \\:=\\:E.\\left[\\frac{\\epsilon ^2}{2}\\right]_0^{\\epsilon }=\\:\\frac{E}{2}\\cdot \\left(\\frac{\\pi .r.\\theta }{180.L}\\right)^2$$</p>',...
        '<br><p>Imagine that the cylinder of bone was unrolled and laid out flat, it would then be a rectangular cuboid with a volume of:</p><br><p>$$2\\pi r.L.dr$$.</p><br>',...
        '<p>When this expression for volume is multiplied by the expression for energy stored per unit volume, the resulting expression for strain energy stored can be simplified to:</p>',...
        '<br><p>$$dW=\\frac{\\pi ^3.E.r^3}{L}\\left(\\frac{\\theta }{180}\\right)^2.dr$$</p>',...
        '<br><p><p>Part C</b></p><p>By the integrating this expression between the limits of <i>r<sub>o</sub></i> and <i>r<sub>o</sub>-t</i>, we obtain the following expression for total strain energy stored in the bone:</p>',...
        '<br><p>$$W=\\frac{\\pi ^3.E}{L}\\cdot \\left(\\frac{\\theta }{180}\\right)^2\\cdot \\int _{r_o-t}^{r_o}r^3.dr$$</p>',...
        '<br><p>Which gives a final expression of:</p>',...
        '<br><p>$$W=\\frac{\\pi ^3.E}{4.L}\\cdot \\left(\\frac{\\theta }{180}\\right)^2.\\left[r^4\\right]_{r_o-t}^{r_o}$$</p>',...
        '<br><p>Which allows you to calculate the total strain energy stored given all of the parameters given in the question.</p>');
  
hint1 = strcat('<b>HINT</b><p>Remember that strain is simply the ratio of extension to original length.<p><p>Remember that the integral of a stress/strain plot will give you the work done on a material per unit volume. What is the volume of this hollow cylinder?</p><p>Integrate the expression in <b>Part B</b> between the limits of <i>r<sub>o</sub></i> and <i>(r<sub>o</sub>-t)</i> to solve <b>Part C</b>.</p>');

    %Complete question XML code generation
    xmlCode = question_cloze(i, ...
        IDString, ... 
        questionString, ...
        generalFeedbackStr, ...
        hint1,...
        '',...
        '',...
        '',...
        '',...
        '');
    
    %Output
    fprintf(file, xmlCode);
 
end
    
fprintf(file, quiz_end()); %xml closing code
fclose(file);


