file = fopen('Question_6.xml', 'w');
fprintf(file,quiz_start());

mcqStringVertical = cloze_mcq('vertical', 2, ...
        'The Fourier series contains no cosine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions', ...
        'The Fourier series contains no sine functions', 'Correct ! The function f(x) is an even function, and therefore contains no sine functions', ...
        'The Fourier series contains cosine and sine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions', ... 
        'The Fourier series contains no cosine or sine functions', 'Incorrect ! The function f(x) is an even function, and therefore contains no sine functions');
    
    
questionString = strcat('A rectangular function is expressed mathematically as follows : <br> f(x) = 1&nbsp;&nbsp;&nbsp;for&nbsp;&nbsp;&nbsp; -pi/2<&nbsp;x&nbsp;<pi/2 <br>',...
                         'f(x) = 0&nbsp;&nbsp;&nbsp;for&nbsp;&nbsp;&nbsp; -pi <&nbsp;x&nbsp;< pi/2&nbsp;&nbsp;and&nbsp;&nbsp; pi/2 <&nbsp;x&nbsp;< pi','<br>',...
                         'Which of the following descriptions of the Fourier series of f(x) is true:<br>',mcqStringVertical);
                     
                     
                     
xmlCode = question_cloze(i, ...
        'Fourier series', ... 
        questionString, ...
        'Fourier series', ...
        '');
    
%Output
fprintf(file, xmlCode);
fprintf(file, quiz_end()); %xml closing code
fclose(file);