file=fopen('Question_3.xml','w'); 
fprintf(file, quiz_start()); %xml initialization code
for i=1:1:100

x = [1,-1,-1];
pos = randi(length(x));
pos_1 = randi(length(x));
num = x(pos);
num_1 = x(pos_1);
a_1 = randi([1 5],1,1)*num;
b_1 = randi ([6 10],1,1)*num_1;
c_1 = randi([11 15],1,1)*num_1;
d_1 = randi ([16 20],1,1)*num;
det1 = (a_1*d_1) - (b_1*c_1);
det = 1/det1;
syms a b c d
[sola,solb,solc,sold] = solve([a_1*a + b_1*c == 1 , a_1*b + b_1*d == 0 , c_1*a + d_1*c == 0, c_1*b + d_1* d == 1 ],[a,b,c,d]); 

numString_1 = cloze_numerical(double(sola), 0.05, 'Good job!', 'Incorrect, try again');
numString_2 = cloze_numerical(double(solb), 0.05, 'Good job!', 'Incorrect, try again');
numString_3 = cloze_numerical(double(solc), 0.05, 'Good job!', 'Incorrect, try again');
numString_4 = cloze_numerical(double(sold), 0.05, 'Good job!', 'Incorrect, try again');

questionString = strcat ('Solve the following matrix multiplication for A (using inverse): <br><br>',...
'$$\\small BA = I$$<br><br> ',...
'where  $$\\small B = \\begin{pmatrix}',num2str(a_1),' & ',num2str(b_1),' \\\\',num2str(c_1),' & ',num2str(d_1), '\\end{pmatrix}\\:$$<br><br>',...
'       $$\\small A = \\begin{pmatrix}a_{11} & a_{12} \\\\a_{21} & a_{22} \\end{pmatrix}\\:$$<br><br>',...
'and    $$\\small I  = \\begin{pmatrix}1 & 0 \\\\0 & 1 \\end{pmatrix}\\:$$<br><br>',...
'a<sub>11</sub> = ',numString_1,'a<sub>12</sub> = ',numString_2,'<br>a<sub>21</sub> = ',numString_3,'a<sub>22</sub> = ',numString_4);

feedbackString = strcat ('Given the following equation : <br><br>',...
'$$\\small BA = I$$<br><br>',...
'Pre-Multiplying B<sup>-1</sup> on both sides, we get : <br><br>',...
'$$\\small B^{-1}BA = B^{-1}I$$<br><br>',...
'It is known that B<sup>-1</sup>B = I and IX = XI = X where X is any matrix. So,<br><br>',...
'$$\\small A = B^{-1}$$<br><br>',...
'For a 2x2 matrix the inverse can be calculated as follows : <br><br>',...
'$$\\small B = \\begin{pmatrix}b_{11} & b_{12} \\\\b_{21} & b_{22} \\end{pmatrix}\\:$$<br><br>',...
'$$\\small B^{-1} = \\frac{1}{|B|}\\begin{bmatrix}b_{22} & -b_{12} \\\\-b_{21} & b_{11} \\end{bmatrix}\\:$$<br><br>',...
'$$\\small \\Rightarrow \\frac{1}{b_{11}b_{22} - b_{12}b_{21}}\\begin{bmatrix}b_{22} & -b_{12} \\\\-b_{21} & b_{11} \\end{bmatrix}\\:$$<br><br>',...
'Because it is a 2x2 matrix, B<sup>-1</sup> can be calculated using the shorthand,<br><br>',...
'$$\\small B^{-1} = \\frac{1}{(',num2str(a_1),')(',num2str(d_1),') - (',num2str(b_1),')(',num2str(d_1),')}\\begin{bmatrix}',num2str(d_1),' & ',num2str(-b_1),' \\\\',num2str(-c_1),' & ',num2str(a_1),' \\end{bmatrix}\\:$$<br><br>',...
'On solving B<sup>-1</sup>,Comparing the LHS with RHS we get A : <br><br>',...
'$$\\small A = \\begin{pmatrix}a_{11} & a_{12} \\\\a_{21} & a_{22} \\end{pmatrix}\\: = \\begin{bmatrix}',num2str(det*d_1),' & ',num2str(-det*b_1),' \\\\',num2str(-det*c_1),' & ',num2str(det*a_1),' \\end{bmatrix}\\:$$<br><br>',...
'The correct answers are : <br><br>',...
'$$\\small a_{11} = ',num2str(double(sola)),'$$&nbsp;;&nbsp;$$\\small a_{12} = ',num2str(double(solb)),'$$<br>',...
'$$\\small a_{21} = ',num2str(double(solc)),'$$&nbsp;;&nbsp;$$\\small a_{22} = ',num2str(double(sold)),'$$<br><br>');


xmlCode = question_cloze(i, ...
        'Solving equations using matrix', ... 
        questionString, ...
        feedbackString, ...
        '');
        
  fprintf(file, xmlCode);
  
end 
fprintf(file, quiz_end()); %xml closing code
fclose(file);